#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <ctype.h>
#include <math.h>
#include <stdlib.h>

void* getNextField(void* packet, size_t fieldSize, size_t packetSize)
{
    static int count = 0;
    count+=1;

    void* field = calloc(1, fieldSize);
    
    
        
}


int main(void)
{
    //Messy - would usually be generated by a function. 
    size_t packetSize = sizeof(uint8_t) + sizeof(uint16_t);
    uint8_t packet[sizeof(uint8_t) + sizeof(uint16_t)] = {0};
    packet[0] = 55;
    *(uint16_t*)(packet+sizeof(uint8_t)) = 30000;

    //Imaginary sending

    //Read off values
    uint8_t* firstValue = getNextField(packet, sizeof(uint8_t), packetSize);
    uint16_t* secondValue = getNextField(packet, sizeof(uint16_t), packetSize);

    printf("%u %u\n", *firstValue, *secondValue);

    free(firstValue);
    free(secondValue);
}